FROM python:3.10-slim

WORKDIR /data_consumer

COPY ./requirements.txt /data_consumer/requirements.txt

RUN apt-get update \ 
    && apt-get -y install libpq-dev gcc \
    && apt-get clean

RUN pip install -r /data_consumer/requirements.txt \
    && rm -rf /root/.cache/pip

COPY . /data_consumer/